Default: &defaults
  user: root
  password: passwd
  host: localhost
  port: 3306
  database: Monaba
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: Monaba_test
  <<: *defaults

Staging:
  database: Monaba_staging
  poolsize: 100
  <<: *defaults

Production:
  database: Monaba_production
  poolsize: 100
  <<: *defaults
